### PR TITLE
Explain that rehash is now built-in to rbenv

### PR DESCRIPTION
**Pull request by andyw8**
I think this this is worth mentioning to avoid confusion such as 
https://github.com/thoughtbot/laptop/pull/391

### CODE REVIEW

**Comment by nertzy** [comment]
:+1:

**Comment by sralmai** [comment]
:+1:

**Comment by raxod502** [comment]
This would avoid confusion over "why is this repository marked DEPRECATED with no information about what the replacement is?".

**Comment by andyw8** [comment]
@sstephenson @josh @mislav ?

**Pull request closed without merging**
